import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { dbService } from '../services/db';
import emailjs from '@emailjs/browser';
import { Leaf, Mail, Lock, Building2, ArrowRight, AlertCircle, KeyRound, ArrowLeft, CheckCircle2 } from 'lucide-react';

function LoginPage() {
  const [view, setView] = useState('login'); // 'login', 'register', 'verify', 'forgot'
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [companyName, setCompanyName] = useState('');
  
  const [otpCode, setOtpCode] = useState(''); // Generated by system
  const [userOtp, setUserOtp] = useState(''); // Entered by user
  
  const [error, setError] = useState('');
  const [successMsg, setSuccessMsg] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const { login, register, loginWithGoogle } = useAuth();
  const navigate = useNavigate();

  const handleLoginSubmit = async (e) => {
    e.preventDefault();
    if (!email || !password) { setError('Lütfen e-posta ve şifrenizi girin.'); return; }
    setError(''); setIsSubmitting(true);
    
    const result = await login(email, password);
    if (result.success) navigate('/dashboard');
    else setError(result.error);
    
    setIsSubmitting(false);
  };

  const handleGoogleLogin = async () => {
    setError(''); setIsSubmitting(true);
    const result = await loginWithGoogle();
    if (result.success) navigate('/dashboard');
    else setError(result.error);
    setIsSubmitting(false);
  };

  const handleRegisterInitiate = async (e) => {
    e.preventDefault();
    if (!email || !password || !companyName) { setError('Lütfen tüm alanları doldurun.'); return; }
    
    setIsSubmitting(true);
    const { exists } = await dbService.checkEmailExists(email);
    setIsSubmitting(false);
    
    if (exists) {
      setError('Bu e-posta adresi sistemde zaten kayıtlı.');
      return;
    }

    const generatedOtp = Math.floor(100000 + Math.random() * 900000).toString();
    setOtpCode(generatedOtp);
    setView('verify');
    
    const serviceId = import.meta.env.VITE_EMAILJS_SERVICE_ID;
    const templateId = import.meta.env.VITE_EMAILJS_TEMPLATE_ID;
    const publicKey = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;

    if (serviceId && serviceId !== 'BURAYA_YAZIN') {
      try {
        await emailjs.send(serviceId, templateId, {
          to_email: email,
          to_name: companyName,
          otp_code: generatedOtp,
          message: 'Hesabınızı doğrulamak için lütfen bu kodu kullanın.'
        }, publicKey);
      } catch (err) {
        console.error("EmailJS Error:", err);
        setError('E-posta gönderilirken bir hata oluştu.');
      }
    } else {
      alert(`[GERÇEK API EKSİK - SİMÜLASYON]\n\n${email} adresine doğrulama kodu gönderildi.\n\nKODUNUZ: ${generatedOtp}`);
    }
  };

  const handleVerifySubmit = async (e) => {
    e.preventDefault();
    if (userOtp !== otpCode) { setError('Hatalı doğrulama kodu. Lütfen tekrar deneyin.'); return; }
    
    setError(''); setIsSubmitting(true);
    const result = await register(email, password, companyName);
    
    if (result.success) navigate('/dashboard');
    else setError(result.error);
    
    setIsSubmitting(false);
  };

  const handleForgotInitiate = async (e) => {
    e.preventDefault();
    if (!email) { setError('Lütfen kayıtlı e-posta adresinizi girin.'); return; }
    
    setError(''); setIsSubmitting(true);
    try {
      await dbService.resetPassword(email);
      setSuccessMsg('Şifre sıfırlama bağlantısı e-posta adresinize gönderildi. Lütfen e-postanızı kontrol edin.');
      setTimeout(() => {
        setView('login');
        setSuccessMsg('');
      }, 5000);
    } catch (err) {
      setError(err.message);
    }
    setIsSubmitting(false);
  };

  const renderInput = (icon, type, placeholder, value, setValue, label) => (
    <div style={{ marginBottom: '20px' }}>
      {label && <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.9rem', marginBottom: '8px', fontWeight: 500 }}>{label}</label>}
      <div style={{ position: 'relative' }}>
        <div style={{ position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)', color: '#64748b' }}>{icon}</div>
        <input 
          type={type} 
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder={placeholder} 
          style={{ width: '100%', padding: '14px 14px 14px 48px', background: 'rgba(11,17,32,0.8)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: 'white', fontSize: '1rem', outline: 'none', transition: 'border-color 0.2s' }}
          onFocus={(e) => e.target.style.borderColor = '#10b981'}
          onBlur={(e) => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
        />
      </div>
    </div>
  );

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0B1120', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px', fontFamily: "'Inter', sans-serif" }}>
      <div style={{ position: 'absolute', top: 40, left: 40, display: 'flex', alignItems: 'center', gap: '12px', cursor: 'pointer' }} onClick={() => navigate('/')}>
        <Leaf color="#10b981" size={28} />
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#f8fafc', margin: 0, letterSpacing: '-0.5px' }}>Yeşil<span style={{color: '#10b981'}}>Defter</span></h1>
      </div>

      <div style={{ background: 'rgba(15, 23, 42, 0.6)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '24px', padding: '48px', width: '100%', maxWidth: '480px', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)' }}>
        
        <h2 style={{ fontSize: '2rem', fontWeight: 800, color: 'white', marginBottom: '8px', textAlign: 'center' }}>
          {view === 'login' && 'Hoş Geldiniz'}
          {view === 'register' && 'SaaS Hesabı Oluştur'}
          {view === 'verify' && 'E-Posta Doğrulama'}
          {view === 'forgot' && 'Şifremi Unuttum'}
        </h2>
        <p style={{ color: '#94a3b8', textAlign: 'center', marginBottom: '32px' }}>
          {view === 'login' && 'Kurumsal karbon hesabınıza giriş yapın.'}
          {view === 'register' && 'Şirketiniz için yeşil dönüşümü hemen başlatın.'}
          {view === 'verify' && `${email} adresine gönderdiğimiz 6 haneli kodu girin.`}
          {view === 'forgot' && 'Kayıtlı e-posta adresinizi girin, sıfırlama linki gönderelim.'}
        </p>

        {error && (
          <div style={{ background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.2)', color: '#ef4444', padding: '12px 16px', borderRadius: '8px', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.9rem' }}>
            <AlertCircle size={18} />
            {error}
          </div>
        )}

        {successMsg && (
          <div style={{ background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.2)', color: '#10b981', padding: '12px 16px', borderRadius: '8px', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.9rem' }}>
            <CheckCircle2 size={18} />
            {successMsg}
          </div>
        )}

        {/* --- LOGIN VIEW --- */}
        {view === 'login' && (
          <form onSubmit={handleLoginSubmit}>
            {renderInput(<Mail size={20}/>, 'email', 'ornek@firma.com.tr', email, setEmail, 'Kurumsal E-Posta')}
            {renderInput(<Lock size={20}/>, 'password', '••••••••', password, setPassword, 'Şifre')}
            
            <div style={{ textAlign: 'right', marginTop: '-12px', marginBottom: '20px' }}>
              <button type="button" onClick={() => { setView('forgot'); setError(''); setSuccessMsg(''); }} style={{ background: 'none', border: 'none', color: '#0ea5e9', fontSize: '0.9rem', cursor: 'pointer', padding: 0 }}>
                Şifremi Unuttum
              </button>
            </div>

            <button type="submit" disabled={isSubmitting} style={{ width: '100%', background: 'linear-gradient(135deg, #10b981 0%, #0ea5e9 100%)', color: 'white', border: 'none', padding: '16px', borderRadius: '12px', fontWeight: 600, fontSize: '1.1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginBottom: '16px' }}>
              {isSubmitting ? 'Giriş Yapılıyor...' : 'Giriş Yap'} {!isSubmitting && <ArrowRight size={20} />}
            </button>
            
            <div style={{ display: 'flex', alignItems: 'center', margin: '20px 0', color: '#64748b' }}>
              <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)' }}></div>
              <span style={{ padding: '0 10px', fontSize: '0.85rem' }}>VEYA</span>
              <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)' }}></div>
            </div>

            <button type="button" onClick={handleGoogleLogin} disabled={isSubmitting} style={{ width: '100%', background: 'rgba(255,255,255,0.05)', color: 'white', border: '1px solid rgba(255,255,255,0.1)', padding: '16px', borderRadius: '12px', fontWeight: 500, fontSize: '1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', transition: 'background 0.2s' }} onMouseOver={e => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'} onMouseOut={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}>
              <svg width="20" height="20" viewBox="0 0 24 24">
                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
              </svg>
              Google ile Giriş Yap
            </button>
          </form>
        )}

        {/* --- REGISTER VIEW --- */}
        {view === 'register' && (
          <form onSubmit={handleRegisterInitiate}>
            {renderInput(<Building2 size={20}/>, 'text', 'Örn: ABC Tekstil A.Ş.', companyName, setCompanyName, 'Firma Ünvanı')}
            {renderInput(<Mail size={20}/>, 'email', 'ornek@firma.com.tr', email, setEmail, 'Kurumsal E-Posta')}
            {renderInput(<Lock size={20}/>, 'password', '••••••••', password, setPassword, 'Şifre')}
            
            <button type="submit" disabled={isSubmitting} style={{ width: '100%', background: 'linear-gradient(135deg, #10b981 0%, #0ea5e9 100%)', color: 'white', border: 'none', padding: '16px', borderRadius: '12px', fontWeight: 600, fontSize: '1.1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginBottom: '16px' }}>
              {isSubmitting ? 'İşleniyor...' : 'Kayıt Ol'} {!isSubmitting && <ArrowRight size={20} />}
            </button>

            <div style={{ display: 'flex', alignItems: 'center', margin: '20px 0', color: '#64748b' }}>
              <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)' }}></div>
              <span style={{ padding: '0 10px', fontSize: '0.85rem' }}>VEYA</span>
              <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.1)' }}></div>
            </div>

            <button type="button" onClick={handleGoogleLogin} disabled={isSubmitting} style={{ width: '100%', background: 'rgba(255,255,255,0.05)', color: 'white', border: '1px solid rgba(255,255,255,0.1)', padding: '16px', borderRadius: '12px', fontWeight: 500, fontSize: '1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', transition: 'background 0.2s' }} onMouseOver={e => e.currentTarget.style.background = 'rgba(255,255,255,0.1)'} onMouseOut={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}>
              <svg width="20" height="20" viewBox="0 0 24 24">
                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
              </svg>
              Google ile Devam Et
            </button>
          </form>
        )}

        {/* --- OTP VERIFY VIEW --- */}
        {view === 'verify' && (
          <form onSubmit={handleVerifySubmit}>
            {renderInput(<KeyRound size={20}/>, 'text', '123456', userOtp, setUserOtp, 'Doğrulama Kodu')}
            
            <button type="submit" disabled={isSubmitting} style={{ width: '100%', background: '#10b981', color: 'white', border: 'none', padding: '16px', borderRadius: '12px', fontWeight: 600, fontSize: '1.1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
              {isSubmitting ? 'Onaylanıyor...' : 'Hesabı Onayla'} {!isSubmitting && <CheckCircle2 size={20} />}
            </button>
            <div style={{ textAlign: 'center', marginTop: '16px' }}>
              <button type="button" onClick={() => { setView('register'); setUserOtp(''); }} style={{ background: 'none', border: 'none', color: '#94a3b8', fontSize: '0.9rem', cursor: 'pointer' }}>Geri Dön</button>
            </div>
          </form>
        )}

        {/* --- FORGOT PASSWORD INITIATE VIEW --- */}
        {view === 'forgot' && (
          <form onSubmit={handleForgotInitiate}>
            {renderInput(<Mail size={20}/>, 'email', 'ornek@firma.com.tr', email, setEmail, 'Kurumsal E-Posta')}
            
            <button type="submit" disabled={isSubmitting} style={{ width: '100%', background: '#0ea5e9', color: 'white', border: 'none', padding: '16px', borderRadius: '12px', fontWeight: 600, fontSize: '1.1rem', cursor: isSubmitting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
              {isSubmitting ? 'Gönderiliyor...' : 'Sıfırlama Linki Gönder'} {!isSubmitting && <Mail size={20} />}
            </button>
            <div style={{ textAlign: 'center', marginTop: '16px' }}>
              <button type="button" onClick={() => { setView('login'); setError(''); setSuccessMsg(''); }} style={{ background: 'none', border: 'none', color: '#94a3b8', fontSize: '0.9rem', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px', width: '100%' }}><ArrowLeft size={16}/> Giriş Ekranına Dön</button>
            </div>
          </form>
        )}

        {/* Footer Toggles (Only show on Login/Register) */}
        {(view === 'login' || view === 'register') && (
          <div style={{ marginTop: '32px', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '24px' }}>
            <span style={{ color: '#64748b' }}>
              {view === 'login' ? "Hesabınız yok mu?" : "Zaten üye misiniz?"}
            </span>
            <button 
              type="button"
              onClick={() => { setView(view === 'login' ? 'register' : 'login'); setError(''); setSuccessMsg(''); }}
              style={{ background: 'none', border: 'none', color: '#10b981', fontWeight: 600, cursor: 'pointer', fontSize: '1rem', padding: 0 }}
            >
              {view === 'login' ? 'Kayıt Ol' : 'Giriş Yap'}
            </button>
          </div>
        )}

      </div>
    </div>
  );
}

export default LoginPage;
